// function getAllCodes(){
//   let country = {};
//
//   let td = document.querySelectorAll("#table td");
//
//   for(let i = 1; i < td.length; i+=2){
//     country[td[i-1].textContent] = td[i].textContent.toLowerCase();
//   }
//   return country;
// }

let countries = {
  "Afghanistan": "af",
  "Afrique du Sud": "za",
  "Åland, Îles": "ax",
  "Albanie": "al",
  "Algérie": "dz",
  "Allemagne": "de",
  "Allemagne de l'EST": "dd",
  "Andorre": "ad",
  "Angola": "ao",
  "Anguilla": "ai",
  "Antarctique": "aq",
  "Antigua et Barbuda": "ag",
  "Antilles néerlandaises": "an",
  "Arabie Saoudite": "sa",
  "Argentine": "ar",
  "Arménie": "am",
  "Aruba": "aw",
  "Australie": "au",
  "Autriche": "at",
  "Azerbaïdjan": "az",
  "Bahamas": "bs",
  "Bahrein": "bh",
  "Bangladesh": "bd",
  "Barbade": "bb",
  "Bélarus": "by",
  "Belgique": "be",
  "Bélize": "bz",
  "Bénin": "bj",
  "Bermudes": "bm",
  "Bhoutan": "bt",
  "Bolivie (État plurinational de)": "bo",
  "Bonaire, Saint-Eustache et Saba": "bq",
  "Bosnie-Herzégovine": "ba",
  "Botswana": "bw",
  "Bouvet, Ile": "bv",
  "Brésil": "br",
  "Brunéi Darussalam": "bn",
  "Bulgarie": "bg",
  "Burkina Faso": "bf",
  "Burundi": "bi",
  "Cabo Verde": "cv",
  "Caïmans, Iles": "ky",
  "Cambodge": "kh",
  "Cameroun": "cm",
  "Canada": "ca",
  "Chili": "cl",
  "Chine": "cn",
  "Christmas, île": "cx",
  "Chypre": "cy",
  "Cocos/Keeling (Îles)": "cc",
  "Colombie": "co",
  "Comores": "km",
  "Congo": "cg",
  "Congo, République démocratique du": "cd",
  "Cook, Iles": "ck",
  "Corée, République de": "kr",
  "Corée, République populaire démocratique de": "kp",
  "Costa Rica": "cr",
  "Côte d'Ivoire": "ci",
  "Croatie": "hr",
  "Cuba": "cu",
  "Curaçao": "cw",
  "Danemark": "dk",
  "Djibouti": "dj",
  "Dominicaine, République": "do",
  "Dominique": "dm",
  "Egypte": "eg",
  "El Salvador": "sv",
  "Emirats arabes unis": "ae",
  "Equateur": "ec",
  "Erythrée": "er",
  "Espagne": "es",
  "Estonie": "ee",
  "Etats-Unis d'Amérique": "us",
  "Ethiopie": "et",
  "Falkland/Malouines (Îles)": "fk",
  "Féroé, îles": "fo",
  "Fidji": "fj",
  "Finlande": "fi",
  "France": "fr",
  "Gabon": "ga",
  "Gambie": "gm",
  "Géorgie": "ge",
  "Géorgie du sud et les îles Sandwich du sud": "gs",
  "Ghana": "gh",
  "Gibraltar": "gi",
  "Grèce": "gr",
  "Grenade": "gd",
  "Groenland": "gl",
  "Guadeloupe": "gp",
  "Guam": "gu",
  "Guatemala": "gt",
  "Guernesey": "gg",
  "Guinée": "gn",
  "Guinée-Bissau": "gw",
  "Guinée équatoriale": "gq",
  "Guyana": "gy",
  "Guyane française": "gf",
  "Haïti": "ht",
  "Heard, Ile et MacDonald, îles": "hm",
  "Honduras": "hn",
  "Hong Kong": "hk",
  "Hongrie": "hu",
  "Île de Man": "im",
  "Îles mineures éloignées des Etats-Unis": "um",
  "Îles vierges britanniques": "vg",
  "Îles vierges des Etats-Unis": "vi",
  "Inde": "in",
  "Indien (Territoire britannique de l'océan)": "io",
  "Indonésie": "id",
  "Iran, République islamique d'": "ir",
  "Iraq": "iq",
  "Irlande": "ie",
  "Islande": "is",
  "Israël": "il",
  "Italie": "it",
  "Jamaïque": "jm",
  "Japon": "jp",
  "Jersey": "je",
  "Jordanie": "jo",
  "Kazakhstan": "kz",
  "Kenya": "ke",
  "Kirghizistan": "kg",
  "Kiribati": "ki",
  "Koweït": "kw",
  "Lao, République démocratique populaire": "la",
  "Lesotho": "ls",
  "Lettonie": "lv",
  "Liban": "lb",
  "Libéria": "lr",
  "Libye": "ly",
  "Liechtenstein": "li",
  "Lituanie": "lt",
  "Luxembourg": "lu",
  "Macao": "mo",
  "ARYdeMacédoine": "mk",
  "Madagascar": "mg",
  "Malaisie": "my",
  "Malawi": "mw",
  "Maldives": "mv",
  "Mali": "ml",
  "Malte": "mt",
  "Mariannes du nord, Iles": "mp",
  "Maroc": "ma",
  "Marshall, Iles": "mh",
  "Martinique": "mq",
  "Maurice": "mu",
  "Mauritanie": "mr",
  "Mayotte": "yt",
  "Mexique": "mx",
  "Micronésie, Etats Fédérés de": "fm",
  "Moldova, République de": "md",
  "Monaco": "mc",
  "Mongolie": "mn",
  "Monténégro": "me",
  "Montserrat": "ms",
  "Mozambique": "mz",
  "Myanmar": "mm",
  "Namibie": "na",
  "Nauru": "nr",
  "Népal": "np",
  "Nicaragua": "ni",
  "Niger": "ne",
  "Nigéria": "ng",
  "Niue": "nu",
  "Norfolk, Ile": "nf",
  "Norvège": "no",
  "Nouvelle-Calédonie": "nc",
  "Nouvelle-Zélande": "nz",
  "Oman": "om",
  "Ouganda": "ug",
  "Ouzbékistan": "uz",
  "Pakistan": "pk",
  "Palaos": "pw",
  "Palestine, Etat de": "ps",
  "Panama": "pa",
  "Papouasie-Nouvelle-Guinée": "pg",
  "Paraguay": "py",
  "PaysBas": "nl",
  "Pays inconnu": "xx",
  "Pays multiples": "zz",
  "Pérou": "pe",
  "Philippines": "ph",
  "Pitcairn": "pn",
  "Pologne": "pl",
  "Polynésie française": "pf",
  "Porto Rico": "pr",
  "Portugal": "pt",
  "Qatar": "qa",
  "République arabe syrienne": "sy",
  "République centrafricaine": "cf",
  "Réunion": "re",
  "Roumanie": "ro",
  "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord": "gb",
  "Russie, Fédération de": "ru",
  "Rwanda": "rw",
  "Sahara occidental": "eh",
  "Saint-Barthélemy": "bl",
  "Saint-Kitts-et-Nevis": "kn",
  "Saint-Marin": "sm",
  "Saint-Martin (partie française)": "mf",
  "Saint-Martin (partie néerlandaise)": "sx",
  "Saint-Pierre-et-Miquelon": "pm",
  "Saint-Siège": "va",
  "Saint-Vincent-et-les-Grenadines": "vc",
  "Sainte-Hélène, Ascension et Tristan da Cunha": "sh",
  "Sainte-Lucie": "lc",
  "Salomon, Iles": "sb",
  "Samoa": "ws",
  "Samoa américaines": "as",
  "Sao Tomé-et-Principe": "st",
  "Sénégal": "sn",
  "Serbie": "rs",
  "Seychelles": "sc",
  "Sierra Leone": "sl",
  "Singapour": "sg",
  "Slovaquie": "sk",
  "Slovénie": "si",
  "Somalie": "so",
  "Soudan": "sd",
  "Soudan du Sud": "ss",
  "Sri Lanka": "lk",
  "Suède": "se",
  "Suisse": "ch",
  "Suriname": "sr",
  "Svalbard et île Jan Mayen": "sj",
  "Swaziland": "sz",
  "Tadjikistan": "tj",
  "Taïwan, Province de Chine": "tw",
  "Tanzanie, République unie de": "tz",
  "Tchad": "td",
  "Tchécoslovaquie": "cs",
  "Rép.tchèque": "cz",
  "Terres australes françaises": "tf",
  "Thaïlande": "th",
  "Timor-Leste": "tl",
  "Togo": "tg",
  "Tokelau": "tk",
  "Tonga": "to",
  "Trinité-et-Tobago": "tt",
  "Tunisie": "tn",
  "Turkménistan": "tm",
  "Turks-et-Caïcos (Îles)": "tc",
  "Turquie": "tr",
  "Tuvalu": "tv",
  "Ukraine": "ua",
  "URSS": "su",
  "Uruguay": "uy",
  "Vanuatu": "vu",
  "Vatican : voir Saint-Siège": "  ",
  "Venezuela (République bolivarienne du)": "ve",
  "Viet Nam": "vn",
  "Viet Nam (Sud)": "vd",
  "Wallis et Futuna": "wf",
  "Yémen": "ye",
  "Yougoslavie": "yu",
  "Zaïre": "zr",
  "Zambie": "zm",
  "Zimbabwe": "zw"
};
function getCountryCode(pays){
  return countries[pays];
}
